### ISSUE TITLE
Null reference at ReplaceWithText (104)

### ISSUE THREAD

**Issue by ZOXEXIVO** [frankfajardo/OpenXmlWordHelper#1]
`  Run rFldCode = field.Parent as Run;
            Run rBegin = rFldCode.PreviousSibling<Run>();
            Run rSep = rFldCode.NextSibling<Run>();
            Run rText = rSep.NextSibling<Run>(); <----
            Run rEnd = rText.NextSibling<Run>();

            rFldCode.Remove();
            rBegin.Remove();
            rSep.Remove();
            rEnd.Remove();`

**Comment by frankfajardo** [comment]
@ZOXEXIVO Can you provide the Word document and that contains the mergefield you are getting the error on. It might help if you identify which OpenXml SDK version you are using.
